feat: warn for unset development secrets

diff --git a/src/dargstack b/src/dargstack
--- a/src/dargstack
+++ b/src/dargstack
@@ -10,6 +10,9 @@
 # variables exist
 set -o errexit -o pipefail -o noclobber -o nounset
 
+# allow matching of files by glob directly without find
+shopt -s globstar nullglob
+
 # Set color codes for use with echo
 LIGHT_BLUE='\e[94m'
 LIGHT_GREEN='\e[92m'
@@ -114,6 +117,34 @@ function docker_sudo() {
 				sudo -S --preserve-env="$ENV_VARS_TO_PRESERVE" docker "$@"
 		fi
 	fi
+}
+
+guard_valid_config() {
+  valid=$1
+  # shellcheck disable=SC2091
+  if ! $(exit $valid); then
+    echo -e "Deployment of ${LIGHT_BLUE}$PROJECT_NAME${NC} stack for" \
+        "${LIGHT_BLUE}$MODE${NC} aborted due to invalid configuration.\n" \
+        "See warnings above."
+    exit "$valid";
+  fi
+}
+
+function check_secrets_templates() {
+  env=$1
+  valid=0
+
+  for template_path in "src/$env/secrets"/**/*.secret.template
+  do
+    secret_path=${template_path%.template}
+    secret_base_name="${secret_path##*/}"
+    if [[ ! -s "$secret_path" ]]
+    then
+      echo -e "Secret ${secret_path%/*}/${LIGHT_RED}$secret_base_name${NC} missing."
+      valid=1
+    fi
+  done
+  return $valid
 }
 
 function deploy() {
@@ -278,8 +309,13 @@ function deploy() {
 				"../${PROJECT_NAME}_stack/src/development/stack.env" | xargs)
 		fi
 
+    check_secrets_templates "development" || valid=$?
+    guard_valid_config $valid
+
 		export "STACK_DOMAIN=$PROJECT_NAME.test"
 	fi
+
+
 
 	echo -e "Deploying ${LIGHT_BLUE}$PROJECT_NAME${NC} stack for" \
 		"${LIGHT_BLUE}$MODE${NC}..."
